name: Auto rebase (nightly-builds)
on:
  schedule:
    - cron: '0 * * * *' # hourly

  push:
    branches:
    - trigger

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: nightly-builds
          fetch-depth: 0
      - name: Rebase
        uses: ./.github/actions/rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

